# -*- coding: utf-8 -*-
"""streamlit_stock_api

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXwgE7nA_eL_E9S5omnaxRXtENgWVrwv
"""

import streamlit as st
import requests
import json
from fastapi import FastAPI
from starlette.requests import Request
from starlette.responses import JSONResponse
import uvicorn

# Replace with your Finnhub API key
FINNHUB_API_KEY = "csvg4d9r01qq28mn68mgcsvg4d9r01qq28mn68n0"
BASE_URL = "https://finnhub.io/api/v1/"

# Create FastAPI instance
app = FastAPI()

@app.get("/get_price")
def get_stock_price(symbol: str):
    """Fetch real-time stock price for a given symbol."""
    try:
        url = f"{BASE_URL}quote?symbol={symbol}&token={FINNHUB_API_KEY}"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        return JSONResponse(content={"symbol": symbol, "price": data.get('c', 'N/A')})
    except requests.exceptions.RequestException as e:
        return JSONResponse(content={"error": f"Request error: {e}"}, status_code=500)

# Run the FastAPI server via Streamlit
if __name__ == "__main__":
    st.title("📡 Live Stock API Server")
    st.write("Use this API to fetch real-time stock prices via Finnhub.")
    st.write("Example: `/get_price?symbol=AAPL`")
    uvicorn.run(app, host="0.0.0.0", port=8000)